# Generated by Django 4.2 on 2024-07-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0003_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('F', 'Fuego'), ('L', 'Lagartija'), ('A', 'Agua'), ('P', 'Planta'), ('T', 'Tierra'), ('E', 'Eléctrico')], max_length=30),
        ),
    ]
